[build]
  base = "./"
  command = "curl -LJO https://github.com/sass/dart-sass/releases/download/${DART_SASS_VERSION}/dart-sass-${DART_SASS_VERSION}-linux-x64.tar.gz && tar -xf dart-sass-${DART_SASS_VERSION}-linux-x64.tar.gz && rm dart-sass-${DART_SASS_VERSION}-linux-x64.tar.gz && export PATH=/opt/build/repo/dart-sass:$PATH && npm run build"
  publish = "./public/"
  [build.environment]
    DART_SASS_VERSION = "1.71.1"
    HUGO_VERSION = "0.123.7"
    NODE_VERSION = "20.11.1"
    NPM_VERSION="10.5.0"
    TZ="Asia/Kolkata"
[[headers]]
  for = "/*"
  [headers.values]
    content-security-policy = "frame-src www.google.com; media-src 'self' blob:; style-src 'self' 'unsafe-inline';"
[[redirects]]
  force = true
  from = "https://tejal-v8.netlify.app/*"
  status = 301
  to = "https://www.tejalshinde.com/:splat"
[[redirects]]
  from = "/*"
  status = 404
  to = "/404/"