[build]
  command = "npm run build"
  publish = "./dist/"
  [build.environment]
    NODE_VERSION = "20.18.0"
    NPM_VERSION = "10.9.0"

[functions]
  deno_import_map = "./netlify/edge-functions/import_map.json"

[[headers]]
  for = "/_astro/*"
  [headers.values]
    cache-control = "immutable, max-age=31536000, public"

[[redirects]]
  force = true
  from = "https://tejal-v8.netlify.app/*"
  status = 301
  to = "https://www.tejalshinde.com/:splat"

[[redirects]]
  from = "/*"
  status = 404
  to = "/404/"
  