[build]
  base = "/"
  command = "npm run build"
  publish = "public"
  [build.environment]
    HUGO_VERSION = "0.100.1"
    NODE_VERSION = "node"
[functions]
  directory = "functions"
  external_node_modules = ["formidable"]
  node_bundler = "esbuild"
[[headers]]
  for = "/*"
  [headers.values]
    content-security-policy = "default-src 'self' 'unsafe-eval' 'unsafe-inline' blob: data:"
[[redirects]]
  force = true
  from = "/art/"
  status = 301
  to = "/work/#art"
[[redirects]]
  force = true
  from = "/projects/"
  status = 301
  to = "/work/#projects"