[build]
  base = "/"
  command = "npm run build"
  publish = "public"
  [build.environment]
    HUGO_VERSION = "0.92.2"
    NODE_VERSION = "node"
[dev]
  framework = "hugo"
[functions]
  directory = "functions"
  external_node_modules = ["formidable"]
  node_bundler = "esbuild"
[[redirects]]
  force = true
  from = "/api/*"
  status = 200
  to = "/.netlify/functions/:splat"