[build]
  command = "./mtimestore -r && npm run lint && npm run typecheck && npm run build"
  publish = "./dist/"
  [build.environment]
    NODE_VERSION = "24"
    NPM_VERSION = "11.10.1"

[[headers]]
  for = "/_astro/*"
  [headers.values]
    cache-control = "immutable, max-age=31536000, public"

[[headers]]
  for = "/*.m3u8seg"
  [headers.values]
    content-type = "video/mp2t"

[functions]
  deno_import_map = "./netlify/edge-functions/import_map.json"

[[redirects]]
  force = true
  from = "https://tejal-shinde.netlify.app/*"
  status = 301
  to = "https://www.tejalshinde.com/:splat"

[[redirects]]
  force = true
  from = "/images/:w/*"
  status = 200
  to = "/.netlify/images/?url=/:splat&w=:w"
